name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write   # ✅ Enables GitHub OIDC authentication
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js 21.7.3
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'

      - name: Set npm to 10.5.0
        run: npm install -g npm@10.5.0

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Optional: Uncomment if you're using `next export`
      # - name: Export static site
      #   run: npm run export

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"               # Adjust if app is in a subfolder
          output_location: ".next"        # Use "out" if using `next export`
          skip_app_build: true            # ✅ Tells Azure we already built locally

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
